version: 2.0

jobs:
  build:
    branches:
      ignore:
        - gh-pages
    working_directory: ~/code
    docker:
      - image: cimg/android:2022.04
    environment:
      JVM_OPTS: -Xmx3072m -Djava.util.concurrent.ForkJoinPool.common.parallelism=2
      TERM: dumb
    steps:
      - run:
          name: Update SDK
          command: |          
            mkdir "$ANDROID_HOME/licenses" || true
            echo "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
            echo "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
            sdkmanager "platform-tools" "platforms;android-31"
      - checkout
      - run:
          name: Submodule Init
          command: git submodule init
      - run:
          name: Submodule Update
          command: git submodule update
      - run:
          name: Create release.jks
          command: echo $RELEASE_PATH_ENCODED | base64 -d > release.jks
      - run:
          name: Print release.jks
          command: echo $RELEASE_PATH_ENCODED | base64 -d
      - run:
          name: Print release one
          command: echo $RELEASE_PASSWORD
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Assemble Build
          command: |
            ./gradlew app:bundleProduction --no-daemon;

      - store_artifacts:
          path: app/build/outputs/bundle
          destination: aab

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results

