name: Android CI

defaults:
  run:
    shell: bash
on:
  push:
    branches: [ dev , master , 'FEAT/**' , 'FIX/**']
  pull_request:
    branches: [ dev , master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Build Google Apk
        run: ./gradlew assembleDebug
